apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-nfd-
  name: openshift-nfd
  namespace: {{ .Values.operators.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.operators.namespace }}